import os
import tempfile
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas


def generate_pdf(name, fairness, agenda, engagement, verdict, keywords, recommendations):
    fd, path = tempfile.mkstemp(suffix=".pdf")
    os.close(fd)

    c = canvas.Canvas(path, pagesize=A4)
    width, height = A4

    c.setFillColor(colors.HexColor("#0f62fe"))
    c.roundRect(30, height - 95, width - 60, 55, 14, fill=1, stroke=0)

    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 20)
    c.drawString(45, height - 68, "FairMeet Report")
    c.setFont("Helvetica", 10)
    c.drawString(45, height - 84, "Smart Participation and Engagement Insights Platform")

    y = height - 130

    c.setFillColor(colors.HexColor("#f3f8ff"))
    c.setStrokeColor(colors.HexColor("#cfe2ff"))
    c.roundRect(30, y - 95, width - 60, 90, 12, fill=1, stroke=1)

    c.setFillColor(colors.HexColor("#123c73"))
    c.setFont("Helvetica-Bold", 12)
    c.drawString(45, y - 18, "Meeting Summary")

    c.setFont("Helvetica", 11)
    c.drawString(45, y - 40, f"Meeting Name: {name}")
    c.drawString(45, y - 60, f"Fairness Score: {fairness}")
    c.drawString(220, y - 60, f"Agenda Score: {agenda}")
    c.drawString(380, y - 60, f"Engagement: {engagement}")
    c.drawString(45, y - 80, f"Verdict: {verdict}")

    y -= 125

    c.setFillColor(colors.HexColor("#f3f8ff"))
    c.setStrokeColor(colors.HexColor("#cfe2ff"))
    c.roundRect(30, y - 65, width - 60, 60, 12, fill=1, stroke=1)

    c.setFillColor(colors.HexColor("#123c73"))
    c.setFont("Helvetica-Bold", 12)
    c.drawString(45, y - 18, "Top Keywords")

    c.setFont("Helvetica", 11)
    c.drawString(45, y - 42, ", ".join(keywords[:8]) if keywords else "No keywords available")

    y -= 95

    c.setFillColor(colors.HexColor("#f3f8ff"))
    c.setStrokeColor(colors.HexColor("#cfe2ff"))
    c.roundRect(30, y - 170, width - 60, 165, 12, fill=1, stroke=1)

    c.setFillColor(colors.HexColor("#123c73"))
    c.setFont("Helvetica-Bold", 12)
    c.drawString(45, y - 18, "Recommendations")

    c.setFont("Helvetica", 10)
    rec_y = y - 42
    for rec in recommendations[:6]:
        c.drawString(50, rec_y, f"- {rec[:95]}")
        rec_y -= 22

    c.setFillColor(colors.HexColor("#4c6ea8"))
    c.setFont("Helvetica-Oblique", 9)
    c.drawString(30, 20, "Generated by FairMeet")

    c.save()
    return path